from Functions.class_TM import TM
from Functions.class_characters import characters

c = characters()
c.reset()
c.comic_book = 'gibi 15'

pages15 = [[c.beg, c.anj, c.cas, c.ceb, c.mon, c.mag, c.san, c.end],
           [],
           [c.anj, c.cas, c.ceb, c.mon, c.mag, 'Anjinho Substituto'],
           [c.beg, c.cas, c.ceb, c.mon, c.mag, c.mmag, c.fat(), c.child()] + c.shades(4),
           [c.cas, c.ceb, c.mon, c.mag],
           [c.cas, c.ceb, c.mon, c.mag, c.mot(), c.mot(), c.att()] + c.kids(4) + c.shades(4),
           [c.cas, c.ceb, c.mon, c.mag],
           [c.cas, c.ceb, c.mon, c.mag, c.anj],
           [c.cas, c.ceb, c.mon, c.mag, c.anj],
           [c.mon, c.anj],
           [c.mon, c.anj, c.fat()] + c.kids(4),
           [c.mon, c.anj],
           [c.mon, c.anj, c.child(), c.child()],
           [c.cas, c.ceb, c.mon, c.mag, c.anj],
           [c.cas, c.ceb, c.mon, c.mag, c.anj],
           [c.cas, c.ceb, c.mon, c.mag, c.anj],
           [c.anj] + [f'Anjo {i + 1}' for i in range(18)] + [c.end],
           [c.beg, c.ast, 'Povo Alienígena Verde'],
           [c.ast, 'Povo Alienígena Verde', c.end],
           [],
           [c.beg, c.pit, 'Dino'],
           [c.pit, 'Dino', 'Mulher das Cavernas'],
           [c.pit, 'Dino', 'Mulher das Cavernas', c.thu, c.bol, c.var, 'Homem das Cavernas'],
           [c.pit, c.thu, c.bol, c.var, 'Homem das Cavernas'],
           [c.pit, 'Dino', 'Dino 2', c.bol, c.var, 'Homem das Cavernas'],
           [c.pit, 'Dino', 'Dino 2', 'Dino 3', c.bol, c.var, 'Homem das Cavernas', 'Mulher das Cavernas', 'Velha das Cavernas'],
           [c.pit, 'Dino', c.bol, c.var, 'Homem das Cavernas', 'Mulher das Cavernas', 'Velha das Cavernas', 'Mulher das Cavernas 2'] + c.shades(2),
           [c.pit, c.thu, c.bol, c.var, 'Homem das Cavernas', 'Velha das Cavernas', 'Mulher das Cavernas 2'],
           [c.pit, c.thu, c.bol, c.var, 'Homem das Cavernas', 'Velha das Cavernas', 'Mulher das Cavernas 2', 'Mulher das Cavernas 3', 'Mulher das Cavernas 4', 'Mulher das Cavernas 5'],
           [c.pit, c.thu, c.bol, 'Homem das Cavernas', 'Mulher das Cavernas', 'Mulher das Cavernas 4', 'Mulher das Cavernas 5', 'Dino'],
           [c.pit, c.thu, c.bol, c.var, 'Mulher das Cavernas', 'Mulher das Cavernas 4', 'Mulher das Cavernas 5', 'Mulher das Cavernas 6', 'Dino'],
           [c.pit, c.var, c.bol, c.thu, c.end],
           [], # [c.bid] # passatempo
           [], # [c.mon, c.ceb, c.mag, c.min] # correio
           [], # [c.anj, c.cas, c.mag, c.hor] # correio
           [],
           [c.beg, c.mon, c.cas],
           [c.mon, c.san],
           [c.mon],
           [c.mon],
           [c.mon, c.san, c.mmon, c.pmon, c.end],
           [c.beg, c.ceb, c.pceb, c.end],
           [c.beg, 'Nico Demo', c.child()],
           ['Nico Demo', c.child(add = -1), c.child()],
           ['Nico Demo', c.child(add = -1), c.child(), c.end],
           [],
           [c.beg, 'Jimmy', c.bid],
           ['Jimmy', c.bid],
           ['Jimmy', c.bid, c.mon, c.mag],
           ['Jimmy', c.bid, c.bug],
           ['Jimmy', c.bid, c.franj],
           ['Jimmy', c.bid],
           ['Jimmy', c.bid, c.mau, c.end],
           [],
           [c.beg, c.pen, 'Gato 1', 'Gato 2', 'Gato 3', 'Gato 4', 'Gato 5', c.end],
           [c.beg, c.ceb], # caricatura da mônica no pc entra? (feito pelo cebolinha)
           [c.ceb, c.mon, c.san, c.blo, c.end], # mônica e sansão na foto recebida pelo cebolinha no pc
           [c.beg, c.nim],
           [c.nim, c.cas],
           [c.nim, c.cas, 'Coelho 1', 'Coelho 2', 'Coelho 3', 'Coelho 4', 'Coelho 5', 'Coelho 6'],
           [c.nim, c.cas],
           [c.nim, c.cas],
           [c.nim, c.cas, 'Pássaro 1', 'Pássaro 2', 'Pássaro 3', 'Pássaro 4', 'Pássaro 5', 'Pássaro 6', 'Pássaro 7', 'Pássaro 8'],
           [c.nim, c.cas, 'Palhaço 1', 'Palhaço 2', 'Palhaço 3', 'Palhaço 4', 'Leão', 'Homem Bala', 'Motoqueiro', 'Bailarina', 'Elefante', 'Atirador'],
           [c.nim, c.cas, c.mcas, c.end],
           [c.beg, c.hum, 'Eco', c.end]] # o eco fala, incluir ele?
