from Functions.class_TM import TM
from Functions.class_characters import characters

c = characters()
c.reset()
c.comic_book = 'gibi 9'

pages9 = [[c.beg, c.ceb, c.cas, c.mon, 'Cebolinha do Futuro', c.end],
          [],
          [c.ceb, c.cas, c.mon, 'Cebolinha do Futuro'],
          [c.beg, c.cas, c.ceb],
          [c.cas, c.ceb, c.fat(), c.child(), c.child(), c.child(), c.child(). c.fig(), 'Cebolinha do Futuro'],
          [c.cas, 'Cebolinha do Futuro', c.child()],
          [c.cas, c.ceb, 'Cebolinha do Futuro'],
          [c.ceb, 'Cebolinha do Futuro'],
          [c.ceb, 'Cebolinha do Futuro'],
          [c.ceb, 'Cebolinha do Futuro'],
          [c.ceb, 'Cebolinha do Futuro', 'Filho do Cebolinha do Futuro', 'Franjinha do Futuro', c.child(), c.child(), c.child(), c.child()],
          [c.cas, c.ceb, 'Cebolinha do Futuro'],
          [c.cas, c.ceb, 'Cebolinha do Futuro'],
          [c.cas, c.ceb, 'Cebolinha do Futuro'],
          [c.cas, c.ceb, 'Cebolinha do Futuro', c.pcas],
          [c.child(), c.child(), c.ceb, 'Cebolinha do Futuro', c.um, c.zvam],
          [c.ceb, 'Cebolinha do Futuro'],
          [c.ceb, 'Cebolinha do Futuro', c.mon, c.san],
          [c.ceb, 'Cebolinha do Futuro', c.mon, c.san],
          [c.ceb, 'Cebolinha do Futuro', c.mon, c.san],
          [c.ceb, 'Cebolinha do Futuro', c.mon, c.mot(), c.child(), c.child()],
          [c.ceb, 'Cebolinha do Futuro', c.mon],
          [c.ceb, 'Cebolinha do Futuro', c.mon, 'Mônica do Futuro', 'Filho do Cebolinha do Futuro', c.end],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          [],
          []]
