from Functions.class_TM import TM
from Functions.class_characters import characters

c = characters()
c.reset()
c.comic_book = '1tmj_04'

cap1 = [[c.beg, c.mon, c.ceb, c.end], #capa
        #[],
        #[],
        #[],
        #[],
        #[],
        [c.beg, c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe] + c.figs(2) + c.shades(2),
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.fig(add=-1), c.fig(add=0), c.shade(add=-1), c.shade(add=0)],
        [c.ceb, c.cas, c.coe, c.tar],
        [c.ceb, c.cas, c.coe, c.tar, 'Filho 58', c.mon, c.jot], #[1/3, [c.ceb, c.cas, c.coe, c.tar, 'Filho 58'[, [c.mon, c.jot]]
        [c.mon, c.ceb, c.jot],
        [c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, c.yuk],
        [c.cap, c.yuk, 'Le Kin', 'Don Dinho', 'Espinho', 'Garra de Aço'],
        [c.cap, c.yuk],
        [c.rap, 'Guarda Macaco 1'] + c.figs(5) + c.shades(10),
        [c.rap, c.rei, c.cax, 'Cameraman 1', 'Repórter 1'] + c.figs(2) + c.shades(3),
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.fig(n=7)] + c.figs(3) + c.shades(4), #A partir daqui ignorei shades
        [c.mon, c.ceb, c.cas, c.rap, c.cap, 'Espinho', 'Lun Chi', c.fig(add=-1), c.fig(add=0), c.fig(n=7)] + c.figs(4),
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.yuk],
        [c.mon, c.ceb, c.cas, c.coe, c.rap, 'Le Kin', 'Garra de Aço', 'Cameraman 1', 'Repórter 1', 'Lutador 1', 'Lutador 2'] + c.figs(2),
        [c.mon, c.mag, c.coe, c.rap, c.yuk, 'Don Dinho'] + c.figs(5),
        [c.mon, c.ceb, c.coe, c.rap, 'Espinho'] + c.figs(4),
        [c.mon, c.ceb, c.coe, c.rap, 'Espinho'], 
        [c.mon, c.ceb, c.coe, c.cap, 'Tiozão', 'Sobrinho 1', 'Sobrinho 2', c.fig()], #DUVIDA
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, 'Garra de Aço', c.cap, 'Tiozão'], #DIVIDIR
        [c.mon, c.ceb, c.cas, c.coe, 'Le Kin'],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, 'Le Kin'],
        [c.cap, 'Tiozão', 'Sobrinho 1', 'Sobrinho 2', c.end]]
cap2 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.cap, 'Cameraman 1', 'Repórter 1'],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.cap, 'Cameraman 1', 'Repórter 1'],
        [c.mon, c.ceb, c.cas, c.coe],
        [c.mon, c.ceb, c.coe, 'Espinho'],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, 'Garra de Aço', 'Cameraman 1', 'Repórter 1'],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, 'Garra de Aço'],
        [c.ceb, c.cas, c.rap, 'Garra de Aço'],
        [c.mon, c.ceb, c.mag, c.cas, c.eeur],
        [c.cas, c.coe, c.rap, 'Espinho'],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.eeur], #ETERNA DUVIDA
        [c.mon, c.ceb, c.cas, c.rap, 'Espinho'],
        [c.cas, c.rap, 'Espinho'],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.cap], #DIVIDIR
        [c.cap, 'Tiozão', c.rei, c.cax, 'Guarda Macaco 1', c.mon, c.ceb, c.mag, c.cas, c.coe], #DIVIDIR
        [c.mon, c.ceb, c.mag, c.cas, c.rei, c.cax],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, 'Filho 97', c.end]]
cap3 = [[c.beg, c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.enot],
        [c.mon, c.enot],
        [c.mon, c.ceb, c.mag, c.cas, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.yuk, 'Lobisomem 1', 'Lobisomem 2'],
        [c.mon, c.ceb, c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, c.yuk],
        [c.mon, c.ceb, c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.cap],
        [c.cap],
        [c.mar, c.den, c.marcas],
        [c.anj, c.mar, c.den, c.marcas],
        [c.anj, c.mar, c.den, c.marcas],
        [c.anj, c.mar, c.den, c.marcas],
        [c.anj, c.mar, c.den, 'Dragão de Poeira'], #Dividir
        [c.anj, c.mar, c.den, c.marcas],
        [c.anj, c.mar, c.den, c.marcas],
        [c.anj, c.mar, c.den, c.marcas, c.cap, 'Monstro de Poeira 1', 'Monstro de Poeira 2'],
        [c.cap],
        [c.anj, c.mar],
        [c.anj, c.mar, c.den, c.marcas, 'Monstro de Poeira 1', 'Monstro de Poeira 2'], #Ligação
        [c.mon, c.ceb, c.mag, c.cas, 'Lobisomem 1', 'Lobisomem 2', 'Lobisomem 3'],
        [c.mon, c.ceb, c.mag, c.cas, 'Lobisomem 1', 'Lobisomem 2', 'Lobisomem 3'],
        [c.mon, c.ceb, c.cas, 'Lobisomem 3'],
        [c.mon, c.ceb, c.mag, c.pen, 'Lobisomem 2'],
        [c.mon, c.ceb, c.mag, c.cas, c.pen, c.mum, c.zvam, 'Lobisomem 1'],
        [c.franj, c.cap],
        [c.franj, c.fal, c.cap],
        [c.franj, c.nim, c.doc, c.mar, c.den, c.cap],
        [c.xav, c.dud, c.tit, c.quin, c.nim, c.anj, c.carfru, c.jer, c.dor, c.luc, c.franj, c.mar, c.doc, c.den, c.marcas, c.bid, c.cap],
        [c.xav, c.dud, c.tit, c.quin, c.nim, c.anj, c.carfru, c.jer, c.dor, c.luc, c.franj, c.mar, c.doc, c.den, c.marcas, c.bid, c.cap],
        [c.franj, c.mar, c.cap, 'Monstro de Poeira 1', 'Monstro de Poeira 2', 'Monstro de Poeira 3', 'Monstro de Poeira 4'],
        [c.mag, c.cas, c.mum, c.zvam],
        [c.mag, c.cas],
        [c.mag, c.cas, c.mum, c.zvam, 'Monstro 1'],
        [c.mag, c.cas, c.mum, c.zvam, 'Monstro 1'],
        [c.mon, c.ceb, c.mag, c.cas, c.pen, c.mor],
        [c.mon, c.mag, c.cas, c.mor],
        [c.mon, c.ceb, c.mag, c.cas, c.pen, c.zvam, c.mor],
        [c.mon, c.ceb, c.mag, c.cas, c.zvam],
        [c.mon, c.ceb, c.mag, c.cas, c.pen, c.mum, c.zvam, c.mor],
        [c.franj, c.mar, 'Monstro de Poeira 1'],
        [c.franj, c.mar, c.bid, 'Monstro 2'],
        [c.franj, c.anj, c.mar, c.bid, c.lou, 'Monstro de Poeira 2', 'Monstro 3'],
        [c.den, c.carfru, c.cap, c.end]]
cap4 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.dor, c.cap],
        [c.mon, c.ceb, c.mag, c.cas, c.dor, c.cap],
        [c.mon, c.ceb, c.mag, c.cas, c.den, c.cap],
        [c.mon, c.cas, c.franj, c.tit, c.mar],
        [c.mon, c.ceb, c.cas, c.den, c.ebor, c.cap, c.pit],
        [c.mon, c.ceb, c.den, c.ebor],
        [c.mon, c.ceb, c.cas, c.anj],
        [c.mon, c.ceb, c.mag, c.cas, c.anj],
        [c.mon, c.ceb, c.mag, c.cas, c.anj],
        [c.mon, c.cap],
        [c.mon, c.ebor, c.cap],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor, c.cap],
        [c.mag, c.cas, c.franj, c.quin, c.mar, c.marcas, c.cap, c.pit],
        [c.mag, c.quin, c.dud, c.cap, 'Policial 1', 'Policial 2'],
        [c.mon, c.ceb, c.cas, c.ebor, c.cap, 'Policial 1', 'Policial 2'],
        [c.mon, c.ceb, c.ebor, c.ezep, c.eeur, c.enot],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.mmon, c.pceb, c.mmag, c.pcas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor, c.ezep, c.eeur, c.enot],
        [c.mon, c.ceb, c.mag, c.xav, c.pceb, c.pcas, 'Formiga 3'],
        [c.mon, c.mag, c.juc],
        [c.mon, c.ceb, c.mag, c.cas, c.juc],
        [c.mon, c.ceb, c.juc, c.pit],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.mar, c.bid],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.end],
        #[],
        #[],
        #[],
        #[],
        #[],
        [c.den, c.ast]] #4 Capa 
        
pages4 = cap1 + cap2 + cap3 + cap4
