from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters()
c.comic_book = '#1tmj_07'
cap4 = [[c.beg, c.mon, c.ceb, c.rob, c.imp, c.end], #Capa - O Brilho de um Pulsar! Parte 2
        [], [], [], [], [],
        [c.beg], #4. Princesa Mimi - Pág 7
        [],
        [],
        [c.usa],
        [c.usa] + c.crowd(name='Robô Tzk'),
        [c.usa] + c.crowd(1),
        [c.usa] + c.crowd(1)[:8],
        [c.imp, c.ID('Guarda Real 1'), c.ID('Guarda Real 2')],
        [c.usa] + c.crowd(1)[:8],
        [c.usa, c.imp, c.ID('Guarda Real 1'), c.ID('Guarda Real 2')],
        [c.usa] + c.crowd(1),
        [c.usa, c.imp] + c.figs(6),
        [c.usa, c.imp],
        [c.usa, c.imp],
        [c.usa, c.imp],
        [c.usa, c.imp],
        [c.usa, c.imp, 'Robô que diz resiliente'],
        [c.usa, c.imp, 'Robô que diz resiliente'],
        [c.mon, c.rob] + [f'#1tmj06 Robô Tzk {i}' for i in range(1,8)],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.xab, c.rob],
        [c.xab, c.ast, c.rob, 'Traje de Combate'],
        [c.rob],
        [c.rob],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.mon, c.ceb, c.franj, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast, c.rob, 'Traje de Combate'],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.mon, c.ceb, c.cas, c.xab],
        [c.ast, c.rob, 'Traje de Combate', c.end]]
cap5 = [[c.beg, c.mon, c.rob], #5. Defenda-se - Pág 46
        [c.mon, c.rob],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.ast, c.rob, 'Traje de Combate'],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast, 'Traje de Combate'],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast, c.rob, 'Traje de Combate'],
        [c.ceb, c.xab],
        [c.ceb, c.xab],
        [c.ceb, c.xab],
        [c.ceb, c.xab] + c.figs(2),
        [c.ceb, c.cas, c.xab],
        [c.ceb, c.cas, c.xab, c.ast],
        [c.ceb, c.cas, c.xab, c.ast],
        [c.ceb, c.cas, c.ast],
        [c.ceb, c.cas, c.xab, c.ast],
        [c.ast],
        [c.rob, c.ID('Robô Pulsar 1')] + c.crowd(name='Guerreiro Robô'),
        [c.ceb, c.cas, c.xab, c.ast],
        [] + c.figs(5) + c.shades(10) + [c.end]]
cap6 = [[c.beg, c.mon, c.mag, c.rob] + c.figs(2), #6. Proteger quem eu amo - Pág 67
        [c.mon, c.mag, c.rob] + c.figs(4),
        [c.mon, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob] + c.figs(2) + c.shades(3),
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.mag, c.rob],
        [c.mon, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.zlui, c.xab, c.ast, c.rob] + c.shades(10),
        [c.franj, c.ast, 'Traje de Combate'],
        [c.franj, c.ast, 'Traje de Combate'],
        [c.franj, c.ast],
        [c.franj, c.ast],
        [2, [c.franj, c.ast], [c.franj, 'Traje de Combate', c.ID('Monstro Alien 1')]],
        [c.franj, c.ast],
        [c.franj, c.ast, 'Traje de Combate'],
        [c.franj, c.zlui, c.ast, c.usa] + c.figs(5),
        [c.mon, c.ceb, c.mag, c.cas, c.xab, c.usa, c.rob],
        [],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.rob],
        [],
        [],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast, c.rob],
        [c.mon, c.mag, c.franj, c.zlui, c.ast, c.rob],
        [c.mon, c.usa],
        [c.usa],
        [c.cas, c.ast, c.usa],
        [c.ceb, c.cas, c.franj, c.xab, c.usa],
        [2, [c.xab] + [f'#1tmj06 Robô Tzk {i}' for i in range(1,6)], [c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast]],
        [c.mon],
        [c.zlui, c.ast] + c.crowd(name='Guerreiro Robô', figs=2),
        [c.fig()] + c.shades(10) + c.crowd(name='Guerreiro Robô'),
        [c.mon, c.ast],
        [c.mon, c.usa, c.rob] + c.crowd(3),
        [c.mon, c.rob],
        [c.mon, c.ceb, c.mag, c.ast, c.rob],
        [c.mon, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.rob],
        [c.mon, c.rob],
        [c.mon, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast, c.usa, c.rob],
        [c.mon, c.ceb, c.xab] + c.crowd(3),
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast] + c.crowd(3),
        [c.mon, c.ceb],
        [c.ceb, c.rob],
        [c.franj, c.ast] + c.crowd(3),
        [c.mon, c.ID('Robô Tzk 11')],
        [c.mon] + c.crowd(name='Robô Tzk', figs=3),
        [c.mon, c.usa],
        [c.mon, c.usa],
        [c.mon, c.usa],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.usa, c.rob],
        [c.usa, c.kam, c.ID('Alien 1')],
        [c.kam, c.ID('Alien 1'), c.end],
        [],
        [],
        [],
        [],
        [],
        [c.van, c.val]] #4 Capa
        
pages7 = cap4 + cap5 + cap6