from Functions.class_TM import TM
from Functions.class_characters import characters

c = characters()
c.reset()
c.comic_book = '1tmj_02'

cap1 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.end], #capa
        #[],
        #[],
        #[],
        #[],
        #[],
        [c.beg, c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ebor],
        [c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.ceb],
        [c.cas],
        [c.mag],
        [c.mon],
        [c.mon, c.ceb, c.mag, c.yuk],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.shade(), c.shade(), c.shade(), c.fig(), c.fig(), c.end]]
cap2 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.van, c.val, 'Elfo', 'Bárbaro', 'Anão 1', 'Anão 2', 'Pet 1', 'Pet 2'],
        [c.mon, c.ceb, c.mag, c.cas, c.van, c.val, 'Elfo', 'Bárbaro', 'Anão 1', 'Anão 2', 'Pet 1', 'Pet 2'],
        [c.ceb, c.val],
        [c.ceb, c.van],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.van, c.val],
        [c.ceb, c.cas, c.van, c.val],
        [c.ceb, c.cas, 'Bárbaro', 'Viking', 'Orc'],
        [c.mon, c.ceb, c.mag, c.cas, c.van, c.val],
        [c.mon, c.ceb, c.cas, 'Bárbaro', 'Viking'],
        [c.mon, c.mag, c.cas, c.van, 'Viking', 'Orc'],
        [c.mon, c.mag, c.van, c.val, 'Bárbaro', 'Orc'],
        [c.mon, c.ceb, c.mag, c.cas, 'Bárbaro', 'Viking', 'Orc'],
        [c.mon, c.ceb, c.mag, c.cas, 'Óinc 1', 'Óinc 2', c.shade(), c.shade(), c.shade(), c.shade(), c.shade()],
        [c.mon, c.ceb, c.mag, c.cas, 'Óinc 1', 'Óinc 2', c.shade(), c.shade(), c.shade(), c.shade(), c.shade()],
        [c.mon, c.ceb, c.cas, 'Óinc 1', c.shade(add=-4), c.shade(add=-3), c.shade(add=-2), c.shade(add=-1), c.shade(add=0)],
        [c.mon, c.ceb, c.mag, 'Óinc 1', 'Óinc 2', 'Óinc 3'],
        [c.mon, c.ceb, c.mag, 'Óinc 1', 'Óinc 2'],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.end]]
cap3 = [[c.beg, c.mon, c.cas],
        [c.ceb, c.mag, c.cas],
        [c.cas, 'Minotauro'],
        [c.mon, c.ceb, c.mag, c.cas, 'Minotauro'],
        [c.ceb, 'Minotauro'],
        [c.mon, c.mag, c.cas],
        [c.mon, c.ceb, 'Minotauro', 'Zarolho'],
        [c.mon, c.ceb, c.cas, 'Minotauro'],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, 'Gigante de Pedra'],
        [c.mon, c.ceb, c.mag, 'Gigante de Pedra'],
        [c.mon, c.ceb, c.mag, c.cas, 'Gigante de Pedra'],
        [c.mon, c.ceb, 'Fada da Ilha Sonífera', 'Duende 1', 'Duende 2', 'Duende 3'],
        [c.mon, c.ceb, c.cas, 'Fada da Ilha Sonífera'],
        [c.mon, c.ceb, c.mag, c.cas, 'Fada da Ilha Sonífera'],
        [c.mon, c.ceb, c.mag, c.cas, 'Fada da Ilha Sonífera', 'Duende 2'],
        [c.mon, c.ceb, 'Fada da Ilha Sonífera'],
        [c.mon, c.ceb, c.mag, c.cas, 'Duende 2'],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, 'Guerreiro Anão 1', 'Arqueiro Anão 1', 'Arqueiro Anão 2', 'Arqueiro Anão 3', 'Arqueiro Anão 4'],
        [c.mag, c.cas, 'Guerreiro Anão 2', 'Guerreiro Anão 3', c.shade(), c.shade(), c.shade(), c.shade(), c.shade(), c.shade(), c.shade()],
        [c.mag, c.cas, c.min, 'Guerreiro Anão 4'],
        [c.mag, c.cas, c.min],
        [c.mag, c.cas, c.min, 'Guerreiro Anão 5', 'Guerreiro Anão 6'],
        [c.mon, c.ceb, c.mag, c.cas, 'Guerreiro Anão 7'],
        [c.mon, c.ceb, c.mag, c.cas, 'Guerreiro Anão 8', 'Guerreiro Anão 9', 'Guerreiro Anão 10'],
        [c.mon, c.ceb, c.mag, c.cas, c.min, 'Guerreiro Anão 10'],
        [c.mon, c.ceb, c.mag, c.cas, c.end]]
cap4 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag],
        [c.mon, c.ceb, c.mag, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.cas, c.cap, 'Guarda Anão 1', 'Guarda Anão 2', 'Guarda Anão 3', 'Guarda Anão 4', 'Guarda Anão 5'],
        [c.mag, c.cas, c.cap, 'Guarda Anão 3', 'Guarda Anão 4'],
        [c.mon, c.ceb, c.cas, c.cap],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, 'Guarda Anão 3', 'Guarda Anão 4'],
        [c.mon, c.ceb, c.cas, c.cap, 'Guarda Anão 6'],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, 'Guarda Anão 2', 'Guarda Anão 3'],
        [c.mon, c.ceb, c.cas, c.cap],
        [c.mon, c.ceb, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.cas, 'General El Osso', 'Esqueleto 1', 'Esqueleto 2', 'Esqueleto 3', 'Esqueleto 4', 'Esqueleto 5', 'Esqueleto 6', 'Esqueleto 7', 'Esqueleto 8', 'Esqueleto 9'],
        [c.mon, c.ceb, c.cas, 'General El Osso', 'Esqueleto 1'],
        [c.cap, c.yuk, 'Guarda Anão 3'],
        [c.mon, c.ceb, c.mag, c.cas, 'Esqueleto 2', 'Esqueleto 3'],
        [c.mon, c.ceb, c.cas, c.ark],
        [c.mon, c.ceb, c.ark],
        [c.ceb, c.mag, c.cas, c.ark],
        [c.ceb, c.mag],
        [c.ceb, c.ark],
        [c.ceb, c.mag, c.cas, c.ark],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.yuk, c.ark],
        [c.mon, c.ceb, c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mag, c.cap, c.yuk, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, c.yuk, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.cas, c.ark],
        [c.mon, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.yuk, c.ark],
        [c.mon, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.ark],
        [c.yuk, c.ark],
        [c.cap, c.yuk],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.yuk, c.end],
        #[],
        #[],
        #[],
        #[],
        #[],
        [c.mag, c.cas]] #4º Capa
        
pages2 = cap1 + cap2 + cap3 + cap4
