from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters()
c.comic_book = '#1tmj_04'
cap12 = [[c.beg, c.mon, c.ceb, c.end], #Capa - Fortes Emoções
         [], [], [], [], [],
         [c.beg, c.mon, c.ceb, c.mag, c.cas, c.coe], #12. O torneio do Disco de Saturno - Pág 7
         [c.mon, c.ceb, c.mag, c.cas, c.coe] + c.figs(2) + c.shades(2),
         [c.mon, c.ceb, c.mag, c.cas, c.coe, c.fig(add=-1), c.fig(add=0), c.shade(add=-1), c.shade(add=0)],
         [c.ceb, c.cas, c.coe, c.tar],
         [2, [c.ceb, c.cas, c.coe, c.tar, 'Filho 58'], [c.mon, c.jot]],
         [c.mon, c.ceb, c.jot],
         [c.mon, c.ceb, c.mag, c.cas, c.coe],
         [c.mon, c.ceb, c.mag, c.coe],
         [c.mon, c.ceb, c.mag, c.cas, c.cap, c.yuk],
         [c.cap, c.yuk, 'Le Kin', 'Don Dinho', 'Espinho', 'Garra de Aço'],
         [c.cap, c.yuk],
         [c.rap, c.ID('Guarda Macaco 1')] + c.crowd(figs=5) + c.crowd(figs=5),
         [c.rap, c.rei, c.cax, c.ID('Cameraman 1'), c.ID('Repórter 1')] + c.crowd(1),
         [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap] + c.crowd(2),
         [2, [c.cap] + c.crowd(2), [c.mon, c.ceb, c.cas, c.rap, 'Espinho', c.ID('Lun Chi')] + c.crowd(1) + c.crowd(2)],
         [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.yuk],
         [c.mon, c.ceb, c.cas, c.coe, c.rap, 'Le Kin', 'Garra de Aço', c.ID('Lutador 1'), c.ID('Lutador 2'), c.ID('Cameraman 1'), c.ID('Repórter 1')] + c.crowd(2),
         [c.mon, c.mag, c.coe, c.rap, c.yuk, 'Don Dinho'] + c.crowd(2),
         [c.mon, c.ceb, c.coe, c.rap, 'Espinho'] + c.crowd(2),
         [c.mon, c.ceb, c.coe, c.rap, 'Espinho'], 
         [2, [c.mon, c.ceb, c.coe] + c.crowd(2), [c.cap, c.ID('Tiozão'), c.ID('Sobrinho 1'), c.ID('Sobrinho 2')] + c.crowd(1)],
         [2, [c.cap, c.ID('Tiozão')], [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, 'Garra de Aço'] + c.crowd(1) + c.crowd(2)],
         [c.mon, c.ceb, c.cas, c.coe, 'Le Kin'],
         [c.mon, c.ceb, c.mag, c.cas, c.coe, 'Le Kin'] + c.crowd(2),
         [c.cap, c.ID('Tiozão'), c.ID('Sobrinho 1'), c.ID('Sobrinho 2'), c.end]] #13. Rumo às finais - Pág. 32
cap13 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.cap, c.ID('Cameraman 1'), c.ID('Repórter 1')] + c.crowd(1) + c.crowd(2),
         [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.cap, c.ID('Cameraman 1'), c.ID('Repórter 1')] + c.crowd(1) + c.crowd(2),
         [c.mon, c.ceb, c.cas, c.coe],
         [c.mon, c.ceb, c.coe, 'Espinho'] + c.crowd(1) + c.crowd(2),
         [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, 'Garra de Aço', c.ID('Cameraman 1'), c.ID('Repórter 1')] + c.crowd(1) + c.crowd(2),
         [c.mon, c.ceb, c.mag, c.cas, c.coe, 'Garra de Aço'] + c.crowd(1) + c.crowd(2),
         [c.ceb, c.cas, c.rap, 'Garra de Aço'] + c.crowd(1),
         [c.mon, c.ceb, c.mag, c.cas, c.eeur],
         [c.cas, c.coe, c.rap, 'Espinho'] + c.crowd(1) + c.crowd(2),
         [2, [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rap, c.eeur], [c.cap]], #DUVIDA
         [c.mon, c.ceb, c.cas, c.rap, 'Espinho'] + c.crowd(1),
         [c.cas, c.rap, 'Espinho'] + c.crowd(1), c.crowd(2),
         [2, [c.mon, c.ceb, c.mag, c.cas, c.coe], [c.cap]], #DUVIDA
         [2, [c.cap, c.ID('Tiozão')], [c.mon, c.ceb, c.mag, c.cas, c.coe, c.rei, c.cax, c.ID('Guarda Macaco 1')]],
         [c.mon, c.ceb, c.mag, c.cas, c.rei, c.cax],
         [c.franj, c.fal, c.cap, c.yuk],
         [c.cap, c.yuk],
         [c.cap, c.yuk],
         [c.mon, c.ceb, c.mag, c.cas, c.coe],
         [c.mon, c.ceb, c.mag, c.cas, c.coe, c.ID('Filho 97'), c.end]]
cap14 = [[c.beg, c.mon, c.ceb, c.mag, c.cas], #14. Edom - Pág 52
         [c.mon, c.ceb, c.mag, c.cas],
         [c.mon, c.ceb, c.mag, c.cas, c.enot],
         [c.mon, c.enot],
         [c.mon, c.ceb, c.mag, c.cas, c.yuk],
         [c.mon, c.ceb, c.mag, c.cas, c.yuk, c.ID('Lobisomem 1'), c.ID('Lobisomem 2')],
         [c.mon, c.ceb, c.cap, c.yuk],
         [c.mon, c.ceb, c.mag, c.cas, c.cap, c.yuk],
         [c.mon, c.ceb, c.cap, c.yuk],
         [c.mon, c.ceb, c.mag, c.cas, c.cap],
         [c.cap],
         [c.mar, c.den, c.marcas],
         [c.anj, c.mar, c.den, c.marcas],
         [c.anj, c.mar, c.den, c.marcas],
         [c.anj, c.mar, c.den, c.marcas],
         [2, [c.anj, c.mar, c.den], [c.anj, 'Dragão de Poeira']],
         [c.anj, c.mar, c.den, c.marcas],
         [c.anj, c.mar, c.den, c.marcas],
         [c.anj, c.mar, c.den, c.marcas, c.cap, '#1tmj01 Monstro de Poeira 1', '#1tmj01 Monstro de Poeira 2'],
         [c.cap],
         [c.anj, c.mar],
         [c.anj, c.mar, c.den, c.marcas, '#1tmj01 Monstro de Poeira 1', '#1tmj01 Monstro de Poeira 2'],
         [c.mon, c.ceb, c.mag, c.cas, c.ID('Lobisomem 1'), c.ID('Lobisomem 2'), c.ID('Lobisomem 3')],
         [c.mon, c.ceb, c.mag, c.cas, c.ID('Lobisomem 1'), c.ID('Lobisomem 2'), c.ID('Lobisomem 3')],
         [c.mon, c.ceb, c.cas, c.ID('Lobisomem 3')],
         [c.mon, c.ceb, c.mag, c.pen, c.ID('Lobisomem 2')],
         [c.mon, c.ceb, c.mag, c.cas, c.pen, c.mum, c.zvam, c.ID('Lobisomem 1')],
         [c.franj, c.cap],
         [c.franj, c.fal, c.cap],
         [c.franj, c.nim, c.doc, c.mar, c.den, c.cap],
         [c.xav, c.dud, c.tit, c.quin, c.nim, c.anj, c.carfru, c.jer, c.dor, c.luc, c.franj, c.mar, c.doc, c.den, c.marcas, c.bid, c.cap],
         [c.xav, c.dud, c.tit, c.quin, c.nim, c.anj, c.carfru, c.jer, c.dor, c.luc, c.franj, c.mar, c.doc, c.den, c.marcas, c.bid, c.cap],
         [c.franj, c.mar, c.cap, '#1tmj01 Monstro de Poeira 1', '#1tmj01 Monstro de Poeira 2', c.ID('Monstro de Poeira 3'), c.ID('Monstro de Poeira 4')],
         [c.mag, c.cas, c.mum, c.zvam],
         [c.mag, c.cas],
         [c.mag, c.cas, c.mum, c.zvam, c.ID('Monstro 1')],
         [c.mag, c.cas, c.mum, c.zvam, c.ID('Monstro 1')],
         [c.mon, c.ceb, c.mag, c.cas, c.pen, c.mor],
         [c.mon, c.mag, c.cas, c.mor],
         [c.mon, c.ceb, c.mag, c.cas, c.pen, c.zvam, c.mor],
         [c.mon, c.ceb, c.mag, c.cas, c.zvam],
         [c.mon, c.ceb, c.mag, c.cas, c.pen, c.mum, c.zvam, c.mor],
         [c.franj, c.mar, '#1tmj01 Monstro de Poeira 1'],
         [c.franj, c.mar, c.bid, c.ID('Monstro 2')],
         [c.franj, c.anj, c.mar, c.bid, c.lou, '#1tmj01 Monstro de Poeira 2', c.ID('Monstro 3')],
         [c.den, c.carfru, c.cap, c.end]]
cap15 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.dor, c.cap], #15. O Retorno - Pág 98
         [c.mon, c.ceb, c.mag, c.cas, c.dor, c.cap],
         [c.mon, c.ceb, c.mag, c.cas, c.den, c.cap],
         [c.mon, c.cas, c.franj, c.tit, c.mar, c.cap],
         [c.mon, c.ceb, c.cas, c.den, c.ebor, c.cap, c.pit],
         [c.mon, c.ceb, c.den, c.ebor],
         [c.mon, c.ceb, c.cas, c.anj],
         [c.mon, c.ceb, c.mag, c.cas, c.anj],
         [c.mon, c.ceb, c.mag, c.cas, c.anj],
         [c.mon, c.cap],
         [c.mon, c.ebor, c.cap],
         [c.mon, c.ceb, c.mag, c.cas, c.ebor, c.cap],
         [c.mag, c.cas, c.franj, c.quin, c.mar, c.marcas, c.cap, c.pit],
         [c.mag, c.quin, c.dud, c.cap, c.ID('Policial 1'), c.ID('Policial 2')],
         [c.mon, c.ceb, c.cas, c.ebor, c.cap, c.ID('Policial 1'), c.ID('Policial 2')],
         [c.mon, c.ceb, c.ebor, c.ezep, c.eeur, c.enot],
         [c.mon, c.ceb, c.mag, c.cas, c.ebor],
         [c.mon, c.mmon, c.pceb, c.mmag, c.pcas, c.ebor],
         [2, [c.mon, c.ebor, c.ezep, c.eeur, c.enot], [c.mon, c.ceb, c.mag, c.cas, c.mmon, c.pceb, c.mmag, c.pcas]],
         [c.mon, c.ceb, c.mag, c.xav, c.pceb, c.pcas, c.ID('Formiga 1')],
         [c.mon, c.mag, c.juc],
         [c.mon, c.ceb, c.mag, c.cas, c.juc],
         [c.mon, c.ceb, c.juc, c.pit],
         [c.mon, c.ceb, c.mag, c.cas, c.franj, c.mar, c.bid],
         [c.mon, c.ceb],
         [c.mon, c.ceb],
         [c.mon, c.ceb, c.mag, c.cas],
         [c.mon, c.ceb, c.mag, c.cas],
         [c.mon, c.ceb, c.mag, c.cas, c.end],
         [],
         [],
         [],
         [],
         [],
         [c.den, c.ast]] #4 Capa  
        
pages4 = cap12 + cap13 + cap14 + cap15
