from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters('#1tmj_10')
cap1 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.end], #Capa - Conta Comigo!
        [], [], [], [c.beg, c.ID('Professor 1')] + c.crowd(figs=0, stus=8), #1. Prólogo - Pág 5
        [c.ceb, c.cas] + c.crowd(1),
        [c.ceb, c.cas] + c.crowd(1),
        [c.mon, c.ceb, c.mag, c.cas] + c.crowd(1),
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon],
        [c.mon],
        [c.mon, c.pmon],
        [c.mon],
        [c.mon, c.end]]
cap2 = [[c.beg, c.mon], #2. Captura de problemas - Pág 17
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb, c.ID('Lutador 1')],
        [c.mon, c.ceb, c.ID('Lutador 1')],
        [c.mon, c.ceb, c.ID('Lutador 1')],
        [c.mon, c.ceb, c.ID('Lutador 1')],
        [c.mon, c.ceb, c.ID('Lutador 1')],
        [c.mon, c.ceb, c.ID('Lutador 2')],
        [c.mon, c.ceb, c.ID('Lutador 2')],
        [c.mon, c.ceb],
        [c.mon, c.ceb, c.ID('Lutador 2')],
        [c.mon, c.ceb],
        [c.mon, c.ID('Lutador 3'), c.ID('Lutador 4'), c.ID('Lutador 5')],
        [c.mon, c.ceb, c.ID('Lutador 3'), c.ID('Lutador 4'), c.ID('Lutador 5')],
        [c.mon, c.ceb, c.ID('Lutador 6'), c.ID('Lutador 7'), c.ID('Lutador 8')],
        [c.mon, c.ceb, 'Lorde Vampiro Imortal das Trevas'],
        [c.mon, c.ceb, 'Lorde Vampiro Imortal das Trevas'],
        [c.mon, c.ceb, 'Lorde Vampiro Imortal das Trevas'],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb],
        [c.mon, c.ceb, c.ID('Lutador 1'), c.ID('Lutador 4'), c.ID('Lutador 5'), c.ID('Lutador 6')],
        [c.mon, c.ceb],
        [c.mon, c.mag, c.end]]
cap3 = [[c.beg, c.cle], #3. Decifra-me ou Devoro-te! - pág 49
        [c.mon, c.mag, c.cle] + c.figs(6),
        [c.mon, c.mag, c.cle] + c.shades(4),
        [c.mon, c.mag],
        [c.mon, c.mag, c.cle],
        [c.mon, c.mag, c.cle, c.shade()] + c.figs(5),
        [c.mon, c.mag, c.den, c.carfru],
        [c.mon, c.mag, c.den, c.carfru],
        [c.mon, c.mag, c.den, c.carfru, c.cle] + c.figs(4),
        [c.mon, c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.mag, c.den, c.carfru, c.cle],
        [c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.mag, c.cle],
        [c.mon, c.mag, c.cle],
        [c.den, c.carfru, c.cle] + c.figs(4) + c.shades(6),
        [c.mon, c.mag, c.cle],
        [c.mon, c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.mag, c.den, c.carfru, c.cle, c.shade()] + c.figs(6),
        [c.mon, c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.mag],
        [c.mon, c.mag],
        [c.mon, c.mag, c.den, c.carfru, c.cle] + c.figs(7),
        [c.mon, c.mag, c.den, c.cle],
        [c.mon, c.mag, c.cle],
        [c.mon, c.mag, c.cle],
        [c.mon, c.den, c.carfru, c.cle],
        [c.mon, c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.den, c.carfru, c.cle],
        [c.mag, c.den, c.carfru, c.cle],
        [c.mon, c.mag, c.den, c.carfru, c.cle, c.ID('Homem Fantasiado de Dinossauro')],
        [c.mon, c.mag, c.cle],
        [c.mon, c.mag, c.cle],
        [2, [c.mon, c.ceb], [c.mon, c.cas], c.end]]
cap4 = [[c.beg, c.cas], #4. Le Parkour! - Pág 83
        [c.cas],
        [c.cas] + c.figs(5) + c.shades(5),
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [2, [] + c.figs(3), [c.mon, c.cas]],
        [c.mon, c.cas, c.kid()] + c.shades(2),
        [c.mon, c.cas], #DUVIDA
        [2, [c.mon, c.cas, c.san], [c.mon, c.cas]],
        [c.mon, c.cas],
        [2, [c.mon, c.cas], [c.ceb, c.cas, c.fig()]],
        [2, [c.mag, c.cas], [c.mon, c.cas]],
        [c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [c.mon, c.cas],
        [2, [c.mon, c.cas], [c.cas, c.fig()]],
        [2, [c.mon, c.cas], [c.mon, c.ceb], c.end]]
cap5 = [[c.beg, c.mon], #5. Por que sempre eu? - Pág 114
        [2, [c.mon, c.ceb], [c.mon, c.mag]],
        [c.mon, c.cas],
        [c.mon, c.mag],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.end],
        [],
        [],
        [],
        [],
        [],
        [],
        [],
        [c.doc]] #4 Capa
        
pages10 = cap1 + cap2 + cap3 + cap4 + cap5