from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters()
c.comic_book = '#1tmj_08'
cap7 = [[c.beg, c.mon, c.ceb, c.usa, c.kam, c.end], #Capa - O Brilho de um Pulsar! Parte Final
        [], [], [], [], [],
        [c.beg, c.usa, c.imp], #7. Corajosa... ou apenas tola - Pág 7
        [c.usa, c.imp],
        [c.usa, c.imp],
        [c.usa, c.imp],
        [c.usa, c.imp, c.rob, '#1tmj_07 Alien 1'],
        [c.usa, c.imp, c.rob],
        [c.usa, c.imp, c.rob, c.kam, '#1tmj_07 Alien 1'],
        [c.usa, c.imp, c.rob, c.kam],
        [c.usa, c.imp, c.rob, c.kam],
        [c.usa, c.imp, c.rob, c.kam],
        [c.usa, c.imp, c.rob, c.kam],
        [c.usa],
        [c.mon, c.usa],
        [c.mon, c.usa] + c.figs(5) + c.crowd(figs=0, shades=10),
        [c.mon, c.ceb, c.usa],
        [c.mon, c.usa, 'Robô que diz resiliente'],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.usa, c.rob],
        [c.mon, c.ceb, c.xab],
        [c.mon, c.usa],
        [c.mon, c.usa],
        [c.mon, c.san],
        [c.mon, c.ceb, c.cas, c.ast, c.usa],
        [c.mon, c.usa],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.usa],
        [c.ceb, c.mag, c.rob],
        [c.mon, c.usa],
        [c.mon, c.usa],
        [c.mon, c.usa],
        [c.mon, c.imp] + c.figs(4), c.crowd(1),
        [c.ceb, c.mag, c.cas, '#1tmj_07 Guerreiro Robô 11'],
        [c.franj, c.zlui, c.ast, '#1tmj_07 Guerreiro Robô 11', '#1tmj_07 Guerreiro Robô 12'],
        [c.franj, c.ast],
        [c.franj, c.ast],
        [c.mon, c.usa],
        [c.mon, c.ceb, c.cas, c.usa, c.rob],
        [c.mon, c.usa],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.rob],
        [c.mon, c.usa],
        [c.mon, c.zlui, c.usa],
        [c.ceb, c.zlui, c.xab, c.usa],
        [c.mon, c.ceb, c.usa],
        [c.mon, c.ceb, c.mag, c.cas, c.xab, c.ast, c.usa],
        [c.usa, c.kam],
        [c.mon, c.usa],
        [c.mon, c.usa, 'Robô que diz resiliente'],
        [c.usa, c.rob],
        [c.mon, c.usa],
        [c.mon, c.usa, c.rob],
        [2, [c.mon, c.usa], [c.usa, c.rob]],
        [c.mon, c.imp, c.rob],
        [c.mon, c.mag, c.usa, c.rob],
        [c.mon, c.usa] + c.crowd(1),
        [2, [c.mon, c.usa] + c.figs(6), [c.mon, c.rob]],
        [c.ceb, c.mag, c.zlui, c.ast, c.rob],
        [2, [c.mon, c.ceb, c.usa], [c.mon, c.ceb, c.xab]],
        [c.mon, c.usa, c.imp],
        [c.mon, c.usa],
        [2, [c.mon, c.mag, c.franj, c.xab, c.usa, c.rob], [c.mon, c.usa, c.imp]],
        [c.mon, c.usa, c.kam],
        [c.mon, c.usa],
        [2, [c.mon, c.ceb, c.mag, c.cas, c.franj, c.ast, c.usa, c.rob], [c.mon, c.usa, c.imp]],
        [c.mon, c.usa, c.kam, c.end]]
cap8 = [[c.beg, c.mon, c.usa, c.kam], #8. Lorde Kamen - Pág 71
        [c.mon, c.usa, c.kam],
        [c.mon, c.usa, c.kam],
        [c.mon, c.usa],
        [c.mon, c.usa, c.kam],
        [c.ceb, c.franj, c.xab, c.ast, c.kam, '#1tmj_07 Guerreiro Robô 11', '#1tmj_07 Guerreiro Robô 12'],
        [c.zlui],
        [],
        [],
        ['#1tmj_07 Guerreiro Robô 13', '#1tmj_07 Guerreiro Robô 14'] + c.figs(3) + c.shades(10),
        [c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.rob, '#1tmj_07 Guerreiro Robô 11', '#1tmj_07 Guerreiro Robô 12'],
        [c.mag, c.franj, c.ast],
        [c.franj, c.ast],
        [c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.rob, '#1tmj_07 Guerreiro Robô 11', '#1tmj_07 Guerreiro Robô 12'],
        [c.zlui, c.ast, c.rob],
        [c.mag, c.ast, c.rob],
        [c.ceb, c.mag, c.cas, c.franj, c.xab, c.ast, c.rob],
        [c.xab, c.ast, c.rob],
        [c.rob],
        [c.rob],
        [c.rob],
        [c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.rob],
        [c.franj, c.zlui, c.ast],
        [c.franj, c.zlui, c.end]]
cap9 = [[c.beg], #9. Configuração de Batalha - Pág 95
        [c.zlui],
        [c.zlui],
        [c.mon, c.usa, c.kam],
        [c.mon, c.usa, c.kam],
        [c.mon, c.usa, 'Robô que diz resiliente'],
        [c.mon, c.usa, c.kam],
        [c.mon, c.usa, c.imp] + c.crowd(1),
        [c.usa, c.rob],
        [c.ast, c.rob],
        [c.mon, c.usa, c.rob, c.kam],
        [c.rob, c.kam],
        [c.rob, c.kam],
        [c.mon, c.usa, c.rob, c.kam],
        [c.usa, c.rob],
        [c.mon, c.usa, c.rob],
        [c.mon, c.usa, c.rob, c.kam],
        [c.imp, c.kam] + c.figs(3) + c.crowd(1),
        [c.mon, c.kam, c.end]]
cap10 = [[c.beg, c.mon, c.usa, c.rob], #10. Epílogo - Pág 114
         [],
         [c.ceb, c.franj, c.zlui, c.xab, c.ast],
         [c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast],
         [c.mon, c.usa, c.imp, c.rob] + c.shades(5),
         [c.mon, c.ceb, c.mag],
         [c.mon, c.ceb, c.xab, c.ast, c.imp],
         [c.cas, c.franj, c.xab, c.ast, c.kam],
         [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.usa, c.imp, c.rob, c.kam, '#1tmj_07 Guerreiro Robô 11', '#1tmj_07 Guerreiro Robô 12'],
         [c.mon, c.ceb, c.cas, c.kam],
         [c.mon, c.ceb, c.usa, c.rob],
         [c.mon, c.ceb, c.franj, c.xab, '#1tmj_07 Guerreiro Robô 11'],
         [c.mon, c.ceb, c.mag, c.cas, c.franj, c.zlui, c.xab, c.ast, c.usa, c.imp, c.rob, c.kam, c.end],
         [],
         [],
         [],
         [],
         [],
         [c.usa, c.imp]] #4 Capa
        
pages8 = cap7 + cap8 + cap8 + cap10