from Functions.class_TM import TM
from Functions.class_characters import characters

c = characters()
c.reset()
c.comic_book = '1tmj_03'

cap1 = [[c.beg, c.mon, c.ceb, 'Kraker', c.end], #capa
        #[],
        #[],
        #[],
        #[],
        #[],
        [c.beg, c.mon, c.ceb, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.rob],
        [c.cas, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.rob],
        [c.ceb, c.cas],
        [c.ceb, c.cas, 'Robô-Ofurô'],
        [c.mon, c.ceb, c.mag, 'Robô-Roupa'],
        [c.mon, c.ceb, c.mag, 'Robô-Cozinheiro'],
        [c.mon, c.ceb, c.mag],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.rob],
        [c.mon, c.ceb, c.mag, c.rob, 'Motox 3D 228 1', 'Motox 3D 228 2'],
        [c.ceb, c.cas, c.rob, 'Motox 3D 228 1'],
        [c.mon, c.ceb, 'Motox 3D 228 1', 'Motox 3D 228 2'],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.franj, c.fal],
        [c.franj, c.mar, c.den, c.marcas],
        [c.mar, c.den, c.marcas, c.end]]
cap2 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.rob, 'Roboy Geórgio', c.fig(), c.fig(), c.fig()],
        [c.mon, c.ceb, c.mag, c.cas, c.rob, 'Roboy Geórgio', c.fig(), c.fig(), c.fig()],
        [c.ceb, c.cas, c.blo, c.rob],
        [c.mon, c.mag, c.blo],
        [c.mag, c.cas, c.blo, c.kra],
        [c.mon, c.ceb, c.mag, c.cas, c.blo],
        [c.mon, c.ceb, c.blo, c.rob],
        [c.mag, c.cas, c.blo],
        [c.mon, c.ceb, c.mag, c.blo],
        [c.mon, c.ceb, c.blo],
        [c.mon, c.blo],
        [c.mon, c.blo, 'Coelho de Ferro'],
        # DUVIDAS ETERNAS
        # DUVIDAS ETERNAS
        [c.cas, 'Motox 3D 228 2', 'Alien Tomboniano 1'],
        [c.mag, 'Robô Fofo 1'],
        [c.mag, 'Robô Fofo 1'],
        [c.ceb, c.spa],
        [c.ceb, c.spa],
        [c.mon, c.blo],
        [c.mon, c.blo, c.kra],
        [c.cas, c.blo, 'Alien Tomboniano 1', 'Alien Tomboniano 2'],
        [c.cas, c.blo, 'Alien Tomboniano 1', 'Alien Tomboniano 2', 'Alien Tomboniano 3', 'Alien Tomboniano 4', 'Alien Tomboniano 5'],
        [c.mag, 'Robô Fofo 1', 'Robô Fofo 2' 'Robô Fofo 3'],
        [c.mag, c.cab],
        [c.franj, c.fal, c.cap, c.cab, c.yuk],
        [c.mag, c.cab],
        [c.ceb, c.blo, c.spa],
        [c.ceb, c.blo, c.spa],
        [c.ceb, c.spa, c.end]]
cap3 = [[c.beg, c.mon, c.blo, c.kra, 'Coelho de Ferro'],
        [c.mon, c.blo, c.kra, 'Coelho de Ferro'],
        [c.cas, c.blo],
        [c.mag, c.cab],
        [c.mag, c.cab],
        [c.mag, c.ast, c.cab],
        [c.mag, c.xab, c.ast, c.cab],
        [c.mag, c.blo, c.ast, c.comp],
        [c.mag, c.blo, c.ast, c.comp],
        [c.mon, c.ceb, c.cas, 'Coelho de Ferro', 'Motox 3D 228 2'],
        [c.mon, c.ceb, c.mag, c.cas, 'Coelho de Ferro'],
        [c.ceb, c.mag, c.cas, c.ast],
        [c.mon, c.ceb, c.mag, c.cas, c.ast, 'Coelho de Ferro'],
        [c.ceb, c.mag, c.cas, c.ast, c.kra],
        [c.ceb, c.ast, c.kra],
        [c.mon, c.ceb, c.mag, c.cas, c.ast, c.kra, 'Coelho de Ferro'],
        [c.mon, c.kra, 'Coelho de Ferro', c.franj, c.fal, c.cap, c.yuk], #[1/3, [c.mon, c.kra, 'Coelho de Ferro'], [c.franj, c.fal, c.cap, c.yuk]]
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.ceb, c.mag, c.cas, c.blo],
        [c.ceb, c.mag, c.cas, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.kra, 'Coelho de Ferro'],
        [c.ceb, c.mag, c.cas, c.blo],
        [c.ceb, c.ast],
        [c.ceb, c.mag, c.cas, c.ast],
        [c.ceb, c.mag, c.cas, c.ast],
        [c.ceb, c.ast, c.cap],
        [c.ceb, c.cas, c.cap, c.kra],
        [c.ceb, c.mag, c.cas, c.ast, c.cap],
        [c.ceb, c.cap],
        [c.ceb, c.mag, c.cas, c.cap, 'Motox 3D 228 2'],
        [c.ceb, c.mag, c.cas, c.blo, c.cap],
        [c.mon, c.ceb, c.kra, 'Coelho de Ferro'],
        [c.mon, c.ceb, 'Coelho de Ferro'],
        [c.mon, c.ceb, c.cap, c.lor],
        [c.mon, c.ceb, c.ast, c.cap, c.lor],
        [c.mon, c.ceb, c.ast, c.cap],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.xab, c.ast, c.comp],
        [c.mon, c.ceb, c.mag, c.cas, c.blo, c.rob],
        [c.mon, c.ceb, c.mag, c.cas, c.blo, 'Coelho de Ferro', c.end]] #FALTAAAAAAAAAA
cap4 = [[c.beg, c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.eeur],
        [c.mon, c.ceb, c.mag, c.cas, c.eeur],
        [c.mon, c.ceb, c.mag, c.cas, 'Formiga 1', 'Formiga 2'],
        [c.mon, c.ceb, c.mag, c.coe],
        [c.mon, c.ceb, c.coe],
        [c.mon, c.ceb, c.cas, c.coe],
        [c.mag, c.mmon, c.pceb, c.mmag, c.pcas, c.coe], #Intrigante
        [c.ceb, c.cas, c.coe, c.eeur],
        [c.mon, c.ceb, c.cas, c.coe],
        [c.mon, c.ceb, c.cas, c.coe],
        ['Imperador', 'Guarda 1'],
        ['Rei Henrique IV', 'Rei James I', 'Dom João V', 'Felipe III'],
        [c.cas, c.coe],
        [c.mmon, c.pceb, c.mmag, c.pcas, 'Imperador'],
        [c.mmon, c.pceb, c.mmag, c.pcas],
        [c.mon, c.coe], #[1/3, [c.mon, c.coe], [c.ebor, c.ezep, c.eeur, c.enot]]
        [c.mon, c.ceb, c.coe],
        [c.mon, c.ceb, c.mag, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.yuk, 'Le Kin', 'Don Dinho', 'Espinho', 'Garra de Aço', c.end],
        #[],
        #[],
        #[],
        #[],
        #[],
        [c.franj, c.mar]] #4º Capa
        
pages3 = cap1 + cap2 + cap3 + cap4
