from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters()
c.comic_book = '#1tmj_02'
cap4 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.end], #Capa - A Aventura Continua!
        [], [], [], [], [],
        [c.beg, c.mon, c.ceb, c.mag, c.cas, c.ebor], #4. Mavidele - Pág 7
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ebor],
        [c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.mon, c.ceb, c.mag, c.cas, c.ebor],
        [c.ceb],
        [c.cas],
        [c.mag],
        [c.mon],
        [c.mon, c.ceb, c.mag, c.yuk],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas] + c.shades(3) + c.figs(2) + [c.end]] #5. O Unicórnio Gêmeo Saltitante - Pág 26
cap5 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.van, c.val, c.ID('Elfo'), c.ID('Bárbaro'), c.ID('Anão 1'), c.ID('Anão 2'), c.anim(), c.anim()],
        [c.mon, c.ceb, c.mag, c.cas, c.van, c.val, c.ID('Elfo'), c.ID('Bárbaro'), c.ID('Anão 1'), c.ID('Anão 2'), c.anim(1), c.anim(2)],
        [c.ceb, c.val],
        [c.ceb, c.van],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.van, c.val],
        [c.ceb, c.cas, c.van, c.val],
        [c.ceb, c.cas, c.ID('Bárbaro'), c.ID('Viking'), c.ID('Orc')],
        [c.mon, c.ceb, c.mag, c.cas, c.van, c.val],
        [c.mon, c.ceb, c.cas, c.ID('Bárbaro'), c.ID('Viking')],
        [c.mon, c.mag, c.cas, c.van, c.ID('Viking'), c.ID('Orc')],
        [c.mon, c.mag, c.van, c.val, c.ID('Bárbaro'), c.ID('Orc')],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Bárbaro'), c.ID('Viking'), c.ID('Orc')],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Óinc 1'), c.ID('Óinc 2')] + c.shades(5),
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Óinc 1'), c.ID('Óinc 2'), c.shade(add=-4), c.shade(add=-3), c.shade(add=-2), c.shade(add=-1), c.shade(add=0)],
        [c.mon, c.ceb, c.cas, c.ID('Óinc 1'), c.shade(add=-4), c.shade(add=-3), c.shade(add=-2), c.shade(add=-1), c.shade(add=0)],
        [c.mon, c.ceb, c.mag, c.ID('Óinc 1'), c.ID('Óinc 2'), c.ID('Óinc 3')],
        [c.mon, c.ceb, c.mag, c.ID('Óinc 1'), c.ID('Óinc 2')],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.end]]
cap6 = [[c.beg, c.mon, c.cas], #6. As Três Torres - Pág 47
        [c.ceb, c.mag, c.cas],
        [c.cas, 'Minotauro'],
        [c.mon, c.ceb, c.mag, c.cas, 'Minotauro'],
        [c.ceb, 'Minotauro'],
        [c.mon, c.mag, c.cas],
        [c.mon, c.ceb, 'Minotauro', c.ID('Zarolho')],
        [c.mon, c.ceb, c.cas, 'Minotauro'],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, 'Gigante de Pedra'],
        [c.mon, c.ceb, c.mag, 'Gigante de Pedra'],
        [c.mon, c.ceb, c.mag, c.cas, 'Gigante de Pedra'],
        [c.mon, c.ceb, 'Fada da Ilha Sonífera', c.ID('Duende 1'), c.ID('Duende 2'), c.ID('Duende 3')],
        [c.mon, c.ceb, c.cas, 'Fada da Ilha Sonífera'],
        [c.mon, c.ceb, c.mag, c.cas, 'Fada da Ilha Sonífera'],
        [c.mon, c.ceb, c.mag, c.cas, 'Fada da Ilha Sonífera', c.ID('Duende 2')],
        [c.mon, c.ceb, 'Fada da Ilha Sonífera'],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Duende 2')],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Guerreiro Anão 1'), c.ID('Arqueiro Anão 1'), c.ID('Arqueiro Anão 2'), c.ID('Arqueiro Anão 3'), c.ID('Arqueiro Anão 4')],
        [c.mag, c.cas, c.ID('Guerreiro Anão 2'), c.ID('Guerreiro Anão 3'), c.shade(), c.shade(), c.shade(), c.shade(), c.shade()],
        [c.mag, c.cas, c.min, c.ID('Guerreiro Anão 4')],
        [c.mag, c.cas, c.min],
        [c.mag, c.cas, c.min, c.ID('Guerreiro Anão 5'), c.ID('Guerreiro Anão 6')],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Guerreiro Anão 7')],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Guerreiro Anão 8'), c.ID('Guerreiro Anão 9'), c.ID('Guerreiro Anão 10')],
        [c.mon, c.ceb, c.mag, c.cas, c.min, c.ID('Guerreiro Anão 10')],
        [c.mon, c.ceb, c.mag, c.cas, c.end]]
cap7 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.yuk], #7. A Feiticeira e o Dragão - Pág 76
        [c.mon, c.ceb, c.mag, c.cas, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag],
        [c.mon, c.ceb, c.mag, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.cas, c.cap, c.ID('Guarda Anão 1'), c.ID('Guarda Anão 2'), c.ID('Guarda Anão 3'), c.ID('Guarda Anão 4'), c.ID('Guarda Anão 5')],
        [c.mag, c.cas, c.cap, c.ID('Guarda Anão 3'), c.ID('Guarda Anão 4')],
        [c.mon, c.ceb, c.cas, c.cap],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, c.ID('Guarda Anão 3'), c.ID('Guarda Anão 4')],
        [c.mon, c.ceb, c.cas, c.cap, c.ID('Guarda Anão 2')],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, c.ID('Guarda Anão 2'), c.ID('Guarda Anão 3')],
        [c.mon, c.ceb, c.cas, c.cap],
        [c.mon, c.ceb, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.cas, c.ID('General El Osso'), c.ID('Esqueleto 1'), c.ID('Esqueleto 2'), c.ID('Esqueleto 3'), c.ID('Esqueleto 4'), c.ID('Esqueleto 5'), c.ID('Esqueleto 6'), c.ID('Esqueleto 7'), c.ID('Esqueleto 8'), c.ID('Esqueleto 9')],
        [c.mon, c.ceb, c.cas, c.ID('General El Osso'), c.ID('Esqueleto 1')],
        [c.cap, c.yuk, c.ID('Guarda Anão 3')],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Esqueleto 2'), c.ID('Esqueleto 3')],
        [c.mon, c.ceb, c.cas, c.ark],
        [c.mon, c.ceb, c.ark],
        [c.ceb, c.mag, c.cas, c.ark],
        [c.ceb, c.mag],
        [c.ceb, c.ark],
        [c.ceb, c.mag, c.cas, c.ark],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.yuk, c.ark],
        [c.mon, c.ceb, c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.cas],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mag, c.cap, c.yuk, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.cap, c.yuk, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.cas, c.ark],
        [c.mon, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.yuk, c.ark],
        [c.mon, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ark],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.ark],
        [c.yuk, c.ark],
        [c.cap, c.yuk],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.yuk, c.end],
        [],
        [],
        [],
        [],
        [c.mag, c.cas]] #4º Capa
        
pages2 = cap4 + cap5 + cap6 + cap7
