from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters()
c.comic_book = '#1tmj_06'
cap1 = [[c.beg, c.mon, c.ceb, c.franj, c.xab, c.ast, c.end], #Capa - O Brilho de um Pulsar!
        [], [], [], [], [],
        [c.mon, c.ceb, c.mag, c.cas, c.xab, c.ast],#, c.], #1. Vamos Subindo - Pág 7
        [c.mon, c.mmon, c.pmon],
        [c.mon, c.mmon, c.pmon],
        [c.mon, c.mag, c.ID('Aeromoça 1')],
        [c.mon, c.mag, c.cas, c.ID('Aeromoça 1')],
        [c.ceb, c.cas],
        [c.mon, c.ceb, c.cas]]
cap2 = [[], #2. O Brilho de um Pulsar - Pág 14
        [],
        [c.mon, c.mmon, c.pmon],
        [c.mmon, c.pmon],
        [c.mmon, c.pmon, c.hor],
        [c.zlui, c.xab, c.ast],
        [c.zlui, c.xab, c.ast],
        [c.zlui, c.xab, c.ast],
        [c.zlui, c.xab],
        [c.zlui, c.xab],
        [c.mon, c.mag, c.franj],
        [c.ceb, c.cas, c.franj],
        [c.mon, c.ceb, c.mag, c.cas, c.franj],
        [c.mon, c.franj],
        [c.mon, c.ceb, c.cas],
        [c.mon, c.ceb],
        [c.ast],
        [c.ceb, c.ast],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.ast],
        [c.ceb, c.cas, c.franj, c.ast],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.ast] + c.shades(5),
        [c.mon, c.mag, c.franj, c.ast],
        [c.mon],
        [c.mon, c.ceb, c.cas],
        [c.mon, c.mag, c.franj],
        [c.franj, c.ast]]
cap3 = [[c.mon, c.mag], #3. Que Demais - Pág 40
        [c.mon, c.mag, c.ID('Jornalista 1')],
        [c.mon, c.mag],
        c.shades(5),
        [c.mon, c.mag],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.franj, c.ast],
        [],
        [c.franj, c.ast],
        [c.franj, c.ast],
        [c.franj, c.ast],
        [2, [c.ast, c.kam], [c.franj, c.ast]],
        [c.mon, c.ceb, c.mag, c.cas, c.franj],
        [c.mon, c.ceb, c.mag, c.cas, c.franj],
        [c.mon], #GIBI
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.xab],
        [c.ceb, c.mag, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.ceb, c.mag, c.xab],
        [c.ceb, c.cas, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mag, c.cas, c.franj],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.mon, c.ceb, c.cas, c.franj],
        [c.mon, c.ceb, c.cas, c.xab] + c.crowd(name='Robô Tzk'),
        [] + c.crowd(1),
        [] + c.crowd(1),
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab] + c.crowd(1),
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab] + c.crowd(1),
        [c.mon, c.mag] + c.crowd(1)[:5],
        [c.mon, c.ceb, c.mag, c.xab, c.crowd(1)[0]],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab],
        [c.ceb, c.mag, c.cas, c.franj, c.xab] + c.crowd(1),
        [c.zlui, c.ast],
        [c.zlui, c.ast],
        [c.zlui, c.ast],
        [c.ast, 'Traje de Combate'],
        [c.mon, c.ceb, c.mag, c.cas, c.franj, c.xab] + c.crowd(1),
        [c.mon, c.ceb, c.franj, c.xab],
        [c.mon, c.ceb, c.franj, c.xab],
        [c.ceb, c.mag, c.cas, c.franj, c.xab] + c.crowd(1),
        [c.xab] + c.crowd(1)[:5],
        [c.mon, c.ceb, c.mag, c.cas, c.franj],
        [c.mon, c.ceb, c.mag, c.cas, c.franj],
        [c.ceb, c.franj] + c.crowd(name='Robô Tzk'),
        [c.ceb, c.cas] + c.crowd(2)[:5],
        [c.mag, c.cas, c.franj] + c.crowd(2),
        [c.ast, 'Traje de Combate'],
        [c.ceb, c.mag, c.cas, c.franj, c.ast, 'Traje de Combate'] + c.crowd(name='Robô Tzk'),
        [c.cas, c.franj, c.ast, 'Traje de Combate'] + c.crowd(3),
        [c.ast, 'Traje de Combate'] + c.crowd(3),
        [c.franj, c.ast, 'Traje de Combate'] + c.crowd(3)[:5],
        [c.franj, c.ast, 'Traje de Combate'] + c.crowd(3)[:5],
        [c.ast, 'Traje de Combate'] + c.crowd(3),
        [c.ast, 'Traje de Combate'] + c.crowd(3),
        [c.ceb, c.mag, c.cas, c.franj, c.ast, 'Traje de Combate'],
        [c.mon, c.xab],
        [c.mon, c.xab] + c.crowd(1)[:3],
        [c.mon, c.xab],
        [c.mon, c.xab] + c.crowd(1)[:5],
        [c.mon] + c.crowd(1)[:6],
        [c.mon, c.xab],
        [c.mon] + c.crowd(1)[:3],
        [c.mon, c.xab] + c.crowd(1),
        [c.rob],
        [c.mon] + c.crowd(1)[:5],
        [c.mon, c.xab],
        [c.mon, c.xab] + c.crowd(1)[:3],
        [c.mon, c.xab, c.rob] + c.crowd(1),
        [c.rob],
        [c.mon, c.xab, c.rob],
        [c.mon, c.xab, c.rob] + c.crowd(1),
        [c.rob] + c.crowd(1),
        [c.rob] + c.crowd(1),
        [c.rob] + c.crowd(1),
        [c.mon, c.xab, c.rob],
        [c.mon, c.xab, c.rob],
        [c.usa, c.ID('Servo Robô 1')],
        [c.usa, c.ID('Servo Robô 1')],
        [c.usa],
        [],
        [],
        [],
        [],
        [],
        [c.tit, c.carfru]] #4 Capa
        
pages6 = cap1 + cap2 + cap3