from Functions.class_TM import TM
from Functions.class_characters import characters
c = characters()
c.comic_book = '#1tmj_03'
cap8 = [[c.beg, c.mon, c.ceb, 'Kraker', c.end], #Capa - Novos Desafios
        [], [], [], [], [],
        [c.beg, c.mon, c.ceb, c.ezep], #8. Tobor - Pág 7
        [c.mon, c.ceb, c.mag, c.cas, c.robs],
        [c.cas, c.robs],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.robs],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.robs],
        [c.ceb, c.cas],
        [c.ceb, c.cas, c.ID('Robô-Ofurô')],
        [c.mon, c.ceb, c.mag, c.ID('Robô-Roupa')],
        [c.mon, c.ceb, c.mag, c.ID('Robô-Cozinheiro')],
        [c.mon, c.ceb, c.mag],
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.robs],
        [c.mon, c.ceb, c.mag, c.robs, c.ID('Motox 3D 228 1'), c.ID('Motox 3D 228 2')],
        [c.ceb, c.cas, c.robs, c.ID('Motox 3D 228 1')],
        [c.mon, c.ceb, c.ID('Motox 3D 228 1'), c.ID('Motox 3D 228 2')],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.franj, c.fal],
        [c.franj, c.mar, c.den, c.marcas],
        [c.mar, c.den, c.marcas, c.end]]
cap9 = [[c.beg, c.mon, c.ceb, c.mag, c.cas, c.robs, c.ID('Roboy Geórgio'), c.fig(), c.fig(), c.fig()], #9. O Grande Mestre - Pág 28
        [c.mon, c.ceb, c.mag, c.cas, c.robs, c.ID('Roboy Geórgio'), c.fig(add=-2), c.fig(add=-1), c.fig(add=0)],
        [c.ceb, c.cas, c.blo, c.robs],
        [c.mon, c.mag, c.blo],
        [c.mag, c.cas, c.blo, c.kra],
        [c.mon, c.ceb, c.mag, c.cas, c.blo],
        [c.mon, c.ceb, c.blo, c.robs],
        [c.mag, c.cas, c.blo],
        [c.mon, c.ceb, c.mag, c.blo],
        [c.mon, c.ceb, c.blo],
        [c.mon, c.blo],
        [c.mon, c.blo, 'Coelho de Ferro'],
        [2, [c.ceb, c.blo], [c.mag, c.blo, c.fig(), c.fig()]],
        [2, [c.cas, c.blo, c.ID('Motox 3D 228 2')], [c.mon, c.blo, 'Coelho de Ferro']],
        [c.cas, c.ID('Motox 3D 228 2'), c.ID('Alien Tomboniano 1')],
        [c.mag, c.ID('Robô Fofo 1')],
        [c.mag, c.ID('Robô Fofo 1')],
        [c.ceb, c.spa],
        [c.ceb, c.spa],
        [c.mon, c.blo],
        [c.mon, c.blo, c.kra],
        [c.cas, c.blo, c.ID('Alien Tomboniano 1'), c.ID('Alien Tomboniano 2')],
        [c.cas, c.blo, c.ID('Alien Tomboniano 1'), c.ID('Alien Tomboniano 2'), c.ID('Alien Tomboniano 3'), c.ID('Alien Tomboniano 4'), c.ID('Alien Tomboniano 5')],
        [c.mag, c.ID('Robô Fofo 1'), c.ID('Robô Fofo 2'), c.ID('Robô Fofo 3')],
        [c.mag, c.cab],
        [c.franj, c.fal, c.cap, c.cab, c.yuk],
        [c.mag, c.cab],
        [c.ceb, c.blo, c.spa],
        [c.ceb, c.blo, c.spa],
        [c.ceb, c.spa, c.end]]
cap10 = [[c.beg, c.mon, c.blo, c.kra, 'Coelho de Ferro'], #10. Batalhas Infinitas - Pág 58
        [c.mon, c.blo, c.kra, 'Coelho de Ferro'],
        [c.cas, c.blo],
        [c.mag, c.cab],
        [c.mag, c.cab],
        [c.mag, c.ast, c.cab],
        [c.mag, c.xab, c.ast, c.cab],
        [c.mag, c.blo, c.ast, c.comp],
        [c.mag, c.blo, c.ast, c.comp],
        [c.mon, c.ceb, c.cas, 'Coelho de Ferro', c.ID('Motox 3D 228 2')],
        [c.mon, c.ceb, c.mag, c.cas, 'Coelho de Ferro'],
        [c.ceb, c.mag, c.cas, c.ast],
        [c.mon, c.ceb, c.mag, c.cas, c.ast, 'Coelho de Ferro'],
        [c.ceb, c.mag, c.cas, c.ast, c.kra],
        [c.ceb, c.ast, c.kra],
        [c.mon, c.ceb, c.mag, c.cas, c.ast, c.kra, 'Coelho de Ferro'],
        [2, [c.mon, c.kra, 'Coelho de Ferro'], [c.franj, c.fal, c.cap, c.yuk]],
        [c.franj, c.fal, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.ceb, c.mag, c.cas, c.blo],
        [c.ceb, c.mag, c.cas, c.ezep],
        [c.mon, c.ceb, c.mag, c.cas, c.ezep, c.kra, 'Coelho de Ferro'],
        [c.ceb, c.mag, c.cas, c.blo],
        [c.ceb, c.ast],
        [c.ceb, c.mag, c.cas, c.ast],
        [c.ceb, c.mag, c.cas, c.ast],
        [c.ceb, c.ast, c.cap],
        [c.ceb, c.cas, c.cap, c.kra],
        [c.ceb, c.mag, c.cas, c.ast, c.cap],
        [c.ceb, c.cap],
        [c.ceb, c.mag, c.cas, c.cap, c.ID('Motox 3D 228 2')],
        [c.ceb, c.mag, c.cas, c.blo, c.cap, c.ID('Motox 3D 228 2')],
        [c.mon, c.ceb, c.kra, 'Coelho de Ferro'],
        [c.mon, c.ceb, 'Coelho de Ferro'],
        [c.mon, c.ceb, c.cap, c.lor],
        [c.mon, c.ceb, c.ast, c.cap, c.lor],
        [c.mon, c.ceb, c.ast, c.cap],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.mon, c.ceb, c.mag, c.cas, c.xab, c.ast, c.comp],
        [c.mon, c.ceb, c.mag, c.cas, c.blo, c.robs],
        [c.mon, c.ceb, c.mag, c.cas, c.blo, 'Coelho de Ferro', c.fig(add=0), c.fig(), c.fig(), c.end]]
cap11 = [[c.beg, c.mon, c.ceb, c.mag, c.cas], #11. Tchalu - Pág 102
        [c.mon, c.ceb, c.mag, c.cas],
        [c.mon, c.ceb, c.mag, c.cas, c.eeur],
        [c.mon, c.ceb, c.mag, c.cas, c.eeur],
        [c.mon, c.ceb, c.mag, c.cas, c.ID('Formiga 1'), c.ID('Formiga 2')],
        [c.mon, c.ceb, c.mag, c.coe],
        [c.mon, c.ceb, c.coe],
        [c.mon, c.ceb, c.cas, c.coe],
        [c.mag, c.mmon, c.pceb, c.mmag, c.pcas, c.coe], #Intrigante
        [c.ceb, c.cas, c.coe, c.eeur],
        [c.mon, c.ceb, c.cas, c.coe],
        [c.mon, c.ceb, c.cas, c.coe],
        ['Imperador Japonês Sec XVI', c.ID('Guarda 1')],
        [c.ID('Rei Henrique IV'), c.ID('Rei James I'), c.ID('Dom João V'), c.ID('Felipe III')],
        [2, [c.cas, c.coe], [c.mmon, c.pceb, c.mmag, c.pcas, 'Imperador Japonês Sec XVI']],
        [c.mmon, c.pceb, c.mmag, c.pcas, 'Imperador Japonês Sec XVI'],
        [c.mmon, c.pceb, c.mmag, c.pcas],
        [2, [c.mon, c.coe], [c.ebor, c.ezep, c.eeur, c.enot]],
        [c.mon, c.ceb, c.coe],
        [c.mon, c.ceb, c.mag, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe],
        [c.mon, c.ceb, c.mag, c.cas, c.coe, c.cap, c.yuk],
        [c.cap, c.yuk],
        [c.yuk, 'Le Kin', 'Don Dinho', 'Espinho', 'Garra de Aço', c.end],
        [],
        [],
        [],
        [],
        [],
        [c.franj, c.mar]] #4º Capa
        
pages3 = cap8 + cap9 + cap10 + cap11
